const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  buttons: state => state.btnrole.permission,
  sySwitch: state => state.app.baseUrl,
  userInfo: state => state.app.userInfo,
  diagramEntity: state => state.app.diagramEntity,
  workTaskNum: state => state.app.workTaskNum,
  componentData: state => state.app.componentData,
  fontColor: state => state.app.fontColor,
  lineDatas: state => state.app.lineDatas,
  isCanvaview: state => state.app.isCanvaview,
  deleNode: state => state.app.deleNode,
}
export default getters
