{
  lazy:false,
  formStyle:{},
  formModes:[
    {
      size: 'mini',
      loading: false,
      display:'inline',
      title: '流程参数',
      dialogVisible:'test',
      dialogShow: true,
      labelWidth:'170px',
      cancelBtnShow:true,
      forms:[
           
      ],
       pointsForModel:[
       			{ field: 'TEXT1', title: '8线保护参数', minWidth: 100, align: "center", queryType: 'text', set: true, require: false, query: false, hide: false },      
    				{ field: 'chargeVoltUp8', title: '充电电压上限(mV)',minWidth: 120,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: true },
            { field: 'chargeCurrUp8', title: '充电过流保护(mV)', minWidth: 100, align: "center", queryType: 'input',set: true, require: false, query: false, hide: false },
            { field: 'chargeCapUp8', title: '充电容量保护(mA)', minWidth: 100, align: "center", queryType: 'input',set: true, require: false, query: false, hide: false },
            { field: 'constCurrVoltFluProtect8', title: '恒流电压波动保护(mV)', minWidth: 100, align: "center", queryType: 'daterange', set: true, require: false, query: false, hide: false},     
            { field: 'constVoltVoltFluProtect8', title: '恒压电压偏差保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
            { field: 'chargeDownContinuousVolt8', title: '充电电压连续下降检测电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
            { field: 'chargeVoltCheckTime8', title: '充电时定时刻电压检测时间',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
            { field: 'chargeCheckVolt8', title: '充电时定时刻检测电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },          
            //{ field: 'STATUS', title: '状态', minWidth: 100, align: "center", queryType: 'switch', set: true, require: false, query: false, hide: false },           
        	//	{ field: 'TEXT', title: 'K值计算', minWidth: 100, align: "center", queryType: 'text', set: true, require: false, query: false, hide: false },           
         		{ field: 'chargeLimitTime8', title: '充电限制时间(s)',minWidth: 120,  align: 'center', queryType: 'switch', set: true, require: false, query: false, hide: false },
         		{ field: 'currentOffset8', title: '恒流电流波动保护(mA)',minWidth: 120,  align: 'center', queryType: 'switch', set: true, require: false, query: false, hide: false },
            //{ field: 'ocvChoose', title: 'OCV选择',minWidth: 100,  align: 'center', queryType: 'select', set: true, require: false, query: false, hide: false },
       			//{ field: 'TEXT1', title: '单盘K值计算', minWidth: 100, align: "center", queryType: 'text', set: true, require: false, query: false, hide: false },      
            { field: 'voltOffset8', title: '恒压电压波动保护(mV)',minWidth: 120,  align: 'center', queryType: 'switch', set: true, require: false, query: false, hide: false },
            { field: 'constVoltRiseContinuous8', title: '恒压电流连续上升保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
            { field: 'voltageRiseInstantlyVolt8', title: '充电瞬间电压上升保护电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
            { field: 'voltageRiseInstantlyTime8', title: '充电瞬间电压上升保护间隔(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
        	 	{ field: 'voltageDropInstantlyVolt8', title: '充电瞬间电压下降保护电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargetotalDropVolt8', title: '充电电压累计下降保护电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'constantVoltRefluxinstantly8', title: '恒压充电电流瞬时回跳(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownCount8', title: '充电电压累计下降次数',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownContinuous8', title: '充电电压连续下降次数',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeVoltLow8', title: '放电电压下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeOverCurrent8', title: '放电过流保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeOverCapa8', title: '放电容量保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeContinuousvoltagerise', title: '放电时电压连续上升检测(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeLimitTime8', title: '放电限制时间(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'underVoltProtect8', title: '放电时电池欠压保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },	
         		{ field: 'dischargeVoltRiseInstant8', title: '放电电压瞬间上升保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'constantcurrentOffset8', title: '恒流时电流偏差保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'currLinevoltDeviation8', title: '电流电压线电压偏差保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'abnormalVoltagevalue8', title: '异常电压变化值(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'LineIRabnormal8', title: '线路电阻异常保护(mΩ)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         
       			{ field: 'TEXT2', title: '9线/10线保护参数', minWidth: 100, align: "center", queryType: 'text', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltUp', title: '充电上限电压(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeCapUp', title: '充电上限容量(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'currentLow', title: '充电电流下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't1Time', title: 'T1时间(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't1TimeLow', title: 'T1时间电压下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't1TimeUp', title: 'T1时间电压上限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't2Time', title: 'T2时间(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't2TimeLow', title: 'T2时间电压下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't2TimeUp', title: 'T2时间电压上限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't3Time', title: 'T3-CC转CV时间下限(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't4Time', title: 'T4-CC转CV时间上限(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't5Time', title: 'T5时间(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't5CurrentLow', title: 'T5时间电流下限(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 't5CurrentUp', title: 'T5时间电流上限(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltOffset', title: '充电电压偏差(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeLimitTime', title: '充电限制时间(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownTime', title: '充电电压下降检查间隔(s)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownValue', title: '充电电压下降值(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'constVoltRise', title: '恒压电流上升幅度(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'constVoltRiseCount', title: '恒压电流上升累计(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'constVoltRiseContinuous', title: '恒压电流上升连续(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownRange', title: '充电电压下降幅度(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownCount', title: '充电电压下降累计(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeVoltDownContinuous', title: '充电电压下降连续(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargeCheckTime', title: '充电检查时刻(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'chargecheckVoltLow', title: '充电检查电压下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'voltVoltLow', title: '放电电压下限(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeTimeLow', title: '放电限制时间(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeCapacityLow', title: '放电下限容量(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeVoltUp', title: '放电电压上升幅度(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeVoltCount', title: '放电电压上升累计(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dischargeVoltContinuous', title: '放电电压上升连续(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'currentOffset', title: '恒流电流偏差(恒流波动保护)(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'overCurrentProtection', title: '过流保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'dormancyLoopCurrent', title: '休眠回路电流(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'overVolt', title: '过压保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'currentLineOverVolt', title: '电流线电压上限(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'cCVoltageDrop', title: '充放电时电压差(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'vlotDiff', title: '休眠时电压差(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'contactImpedance', title: '接触阻抗(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'batteryTempAlarm', title: '电池温度报警(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'scramVolt', title: '急停电压(全局电压上限)(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'v1CollectTime', title: 'V1采样时间(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'voltDropProtection', title: '电压突降保护(mV)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'batteryTempEarlyAlarm', title: '电池温度预警(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
         		{ field: 'currentPercentProtection', title: '电流百分比保护(mA)',minWidth: 100,  align: 'center', queryType: 'input', set: true, require: false, query: false, hide: false },
        
         		
         		
         		
        
      ],
       standTimeforms:[
             { field: 'stl', title: '静置时间下限(H)',minWidth: 120,  align: 'center', queryType: 'input', set: true, require: true, query: false, hide: true },
            { field: 'stu', title: '静置时间上限(H)', minWidth: 100, align: "center", queryType: 'input',set: true, require: true, query: false, hide: false },
        
      ],
    }
  ]
}